### PR TITLE
Calculate

### PR DESCRIPTION
**Pull request by Lukasz-334**
Test-calculate.

### CODE REVIEW

**Comment by ziobron** [comment]
✅ CI Passed - Task: calculate
🏅 Granted 6 XP for @Lukasz-334

**Comment by ziobron** [comment]
⏱ 3 XP extra for @Lukasz-334 for on-time delivery

**Review by gyrydymptum — COMMENTED** [review]
else before return is not needed

**Comment by ziobron** [comment]
Thanks @gyrydymptum for Code Review.
🏅 1 XP granted

**Pull request closed without merging**
