### PR TITLE
Homework Podstawy C++ vector of shared ptrs

### PR DESCRIPTION
**Pull request by Crazyayane07**
Authors: @Crazyayane07, @krzysztof-kryczka

### CODE REVIEW

**Comment by ziobron** [comment]
🏅 +1 XP for cooperation goes to @Crazyayane07

**Comment by ziobron** [comment]
🏅 +1 XP for cooperation goes to @krzysztof-kryczka

**Comment by ziobron** [comment]
✅ CI Passed - Task: vector-of-shared-ptrs
🏅 Granted 5 XP for @Crazyayane07

**Comment by ziobron** [comment]
⏱ 3 XP extra for @Crazyayane07 for on-time delivery

**Comment by ziobron** [comment]
✅ CI Passed - Task: vector-of-shared-ptrs
🏅 Granted 5 XP for @krzysztof-kryczka

**Comment by ziobron** [comment]
⏱ 3 XP extra for @krzysztof-kryczka for on-time delivery

**Review by nauka-programowania-MA — APPROVED** [review]
BEAUTIFUL!!!! I really enjoy your code style.

**Pull request closed without merging**
