### PR TITLE
Vector-of-shared-ptrs

### PR DESCRIPTION
**Pull request by Lukasz-334**
test1.

### CODE REVIEW

**Comment by ziobron** [comment]
✅ CI Passed - Task: vector-of-shared-ptrs
🏅 Granted 5 XP for @Lukasz-334

**Comment by ziobron** [comment]
⏱ 3 XP extra for @Lukasz-334 for on-time delivery

**Review by gyrydymptum — COMMENTED** [review]
You can add an exception, count must be greater than 0.

**Comment by ziobron** [comment]
Thanks @gyrydymptum for Code Review.
🏅 1 XP granted

**Pull request closed without merging**
