### PR TITLE
gen-seq v.1

### PR DESCRIPTION
**Pull request by Lukasz-334**
gen-seq test1.

### CODE REVIEW

**Comment by ziobron** [comment]
✅ CI Passed - Task: generate-sequence
🏅 Granted 5 XP for @Lukasz-334

**Comment by ziobron** [comment]
⏱ 3 XP extra for @Lukasz-334 for on-time delivery

**Review by gyrydymptum — COMMENTED** [review]
non-uniform formatting without the interval  "="

**Comment by ziobron** [comment]
Thanks @gyrydymptum for Code Review.
🏅 1 XP granted

**Pull request closed without merging**
