### PR TITLE
Nwd nnw

### PR DESCRIPTION
**Pull request by Lukasz-334**
nwd-nww test.

### CODE REVIEW

**Comment by ziobron** [comment]
✅ CI Passed - Task: nwd-nnw
🏅 Granted 6 XP for @Lukasz-334

**Comment by ziobron** [comment]
⏱ 3 XP extra for @Lukasz-334 for on-time delivery

**Review by gyrydymptum — COMMENTED** [review]
clear code

**Comment by ziobron** [comment]
Thanks @gyrydymptum for Code Review.
🏅 1 XP granted

**Pull request closed without merging**
