### PR TITLE
Homework: vector-of-shared-pointers

### PR DESCRIPTION
**Pull request by mariuszlisowski**
Authors: @mariuszlisowski, @gyrydymptum

### CODE REVIEW

**Comment by ziobron** [comment]
🏅 +1 XP for cooperation goes to @mariuszlisowski

**Comment by ziobron** [comment]
🏅 +1 XP for cooperation goes to @gyrydymptum

**Comment by ziobron** [comment]
✅ CI Passed - Task: vector-of-shared-ptrs
🏅 Granted 5 XP for @mariuszlisowski

**Comment by ziobron** [comment]
⏱ 3 XP extra for @mariuszlisowski for on-time delivery

**Comment by ziobron** [comment]
✅ CI Passed - Task: vector-of-shared-ptrs
🏅 Granted 5 XP for @gyrydymptum

**Comment by ziobron** [comment]
⏱ 3 XP extra for @gyrydymptum for on-time delivery

**Review by nauka-programowania-MA — APPROVED** [review]
Excellent!

**Pull request closed without merging**
