### PR TITLE
max vec v.1

### PR DESCRIPTION
**Pull request by Lukasz-334**
max vector test

### CODE REVIEW

**Comment by ziobron** [comment]
✅ CI Passed - Task: max-of-vector
🏅 Granted 5 XP for @Lukasz-334

**Comment by ziobron** [comment]
⏱ 3 XP extra for @Lukasz-334 for on-time delivery

**Review by gyrydymptum — COMMENTED** [review]
Undefined behavior when vector is empty.

**Comment by ziobron** [comment]
Thanks @gyrydymptum for Code Review.
🏅 1 XP granted

**Pull request closed without merging**
